### ISSUE TITLE
dcm2bids philips dataset error

### ISSUE THREAD

**Issue by alexfoias** [UNFmontreal/Dcm2Bids#50] opened 2019-05-07 20:05 UTC
I tried to run the dcm2bids on a Philips dataset. The current version of the script & config file doesn't take into account multiple echos.

I'm running the script on OSX 10.14.4 (18E226).

Here is my terminal output:
<details>

~~~

alex-macbook:~ $ dcm2bids -d /Users/alfoi/Desktop/glen -c /Users/alfoi/code/Dcm2Bids/config_spine.txt -p sub-001 -o /Users/alfoi/Desktop/glen
INFO:dcm2bids:--- dcm2bids start ---
INFO:dcm2bids:subprocess: dcm2niix
INFO:dcm2bids:
Chris Rorden's dcm2niiX version v1.0.20180622 (JP2:OpenJPEG) GCC6.1.0 (64-bit MacOS)
usage: dcm2niix [options] <in_folder>
 Options :
  -1..-9 : gz compression level (1=fastest..9=smallest, default 6)
  -b : BIDS sidecar (y/n/o [o=only: no NIfTI], default y)
   -ba : anonymize BIDS (y/n, default y)
  -c : comment stored in NIfTI aux_file (up to 24 characters)
  -d : directory search depth. Convert DICOMs in sub-folders of in_folder? (0..9, default 5)
  -f : filename (%a=antenna  (coil) number, %b=basename, %c=comments, %d=description, %e=echo number, %f=folder name, %i=ID of patient, %j=seriesInstanceUID, %k=studyInstanceUID, %m=manufacturer, %n=name of patient, %p=protocol, %r=instance number, %s=series number, %t=time, %u=acquisition number, %v=vendor, %x=study ID; %z=sequence name; default '%f_%p_%t_%s')
  -g : generate defaults file (y/n/o/i [o=only: reset and write defaults; i=ignore: reset defaults], default n)
  -h : show help
  -i : ignore derived, localizer and 2D images (y/n, default n)
  -l : losslessly scale 16-bit integers to use dynamic range (y/n, default n)
  -m : merge 2D slices from same series regardless of study time, echo, coil, orientation, etc. (y/n, default n)
  -n : only convert this series number - can be used up to 16 times (default convert all)
  -o : output directory (omit to save to input folder)
  -p : Philips precise float (not display) scaling (y/n, default y)
  -r : rename instead of convert DICOMs (y/n, default n)
  -s : single file mode, do not convert other images in folder (y/n, default n)
  -t : text notes includes private patient details (y/n, default n)
  -u : up-to-date check
  -v : verbose (n/y or 0/1/2 [no, yes, logorrheic], default 0)
  -x : crop (y/n, default n)
  -z : gz compress images (y/i/n/3, default y) [y=pigz, i=internal:miniz, n=no, 3=no,3D]
 Defaults file : /Users/alfoi/.dcm2nii.ini
 Examples :
  dcm2niix /Users/chris/dir
  dcm2niix -c "my comment" /Users/chris/dir
  dcm2niix -o /users/cr/outdir/ -z y ~/dicomdir
  dcm2niix -f %p_%s -b y -ba n ~/dicomdir
  dcm2niix -f mystudy%s ~/dicomdir
  dcm2niix -o "~/dir with spaces/dir" ~/dicomdir

INFO:dcm2bids:dcm2niix:version: v1.0.20180622
INFO:dcm2bids:participant: sub-001
INFO:dcm2bids:session: None
INFO:dcm2bids:config: /Users/alfoi/code/Dcm2Bids/config_spine.txt
INFO:dcm2bids:BIDS directory: /Users/alfoi/Desktop/glen
INFO:dcm2bids:
INFO:dcm2bids:Old dcm2niix output found
INFO:dcm2bids:Use --forceDcm2niix to rerun the conversion
INFO:dcm2bids:
INFO:dcm2bids:Sidecars matching:
INFO:dcm2bids:NO MATCH        1001_glen_WIP_GRE-ME_5..20171128160324_e1.json
INFO:dcm2bids:NO MATCH        1001_glen_WIP_GRE-ME_5..20171128160324_e2.json
INFO:dcm2bids:NO MATCH        1001_glen_WIP_GRE-ME_5..20171128160324_e3.json
INFO:dcm2bids:NO MATCH        101_glen_WIP_SURVEY_CL..8160324_e1_i00001.json
INFO:dcm2bids:NO MATCH        101_glen_WIP_SURVEY_CL..1128160324_i00004.json
INFO:dcm2bids:NO MATCH        101_glen_WIP_SURVEY_CL..1128160324_i00007.json
INFO:dcm2bids:NO MATCH        201_glen_WIP_T1w_SENSE_20171128160324.json
INFO:dcm2bids:NO MATCH        301_glen_WIP_T2w_SENSE_20171128160324.json
INFO:dcm2bids:NO MATCH        401_glen_WIP_DWI_CLEAR_20171128160324.json
INFO:dcm2bids:NO MATCH        402_glen_facFAc_20171128160324_e1.json
INFO:dcm2bids:NO MATCH        501_glen_WIP_GRE-MT_Pr..20171128160324_e1.json
INFO:dcm2bids:NO MATCH        701_glen_WIP_GRE-ME_CLEAR_20171128160324_e1.json
INFO:dcm2bids:NO MATCH        701_glen_WIP_GRE-ME_CLEAR_20171128160324_e2.json
INFO:dcm2bids:NO MATCH        701_glen_WIP_GRE-ME_CLEAR_20171128160324_e3.json
INFO:dcm2bids:NO MATCH        801_glen_WIP_GRE-MT_SENSE_20171128160324.json
INFO:dcm2bids:
INFO:dcm2bids:Checking if a description matches several sidecars ...
INFO:dcm2bids:
INFO:dcm2bids:moving acquisitions into BIDS output directory

~~~

</details>

Here is my config file:

<details>

~~~

{
    "descriptions": [
        {
            "dataType": "anat",
            "modalityLabel": "T1w",
            "criteria": {
                "SeriesDescription": "T1w",
                "ProtocolName": "*T1w"
            }
        },
        {
            "dataType": "anat",
            "modalityLabel": "T2w",
            "criteria": {
                "SeriesDescription": "T2w",
                "ProtocolName": "*T2w"
            }
        },
        {
            "dataType": "anat",
            "modalityLabel": "MTS",
            "customLabels": "acq-T1w",
            "criteria": {
                "SeriesDescription": "GRE-T1*",
                "ProtocolName": "*GRE-T1*"
            }
        },
        {
            "dataType": "anat",
            "modalityLabel": "MTS",
            "customLabels": "acq-MT",
            "criteria": {
                "Manufacturer": "Philips",
                "SeriesDescription": "GRE-MT",
                "ProtocolName": "WIP_GRE-MT"
            }
        }, 
        {
            "dataType": "anat",
            "modalityLabel": "MTS",
            "customLabels": "acq-MTon",
            "criteria": {
                "SeriesDescription": "GRE-MT1",
                "ProtocolName": "GRE-MT1"
            }
        },
        {
            "dataType": "anat",
            "modalityLabel": "MTS",
            "customLabels": "acq-MToff",
            "criteria": {
                "SeriesDescription": "GRE-MT0",
                "ProtocolName": "GRE-MT0"
            }
        },

        {
            "dataType": "anat",
            "modalityLabel": "T2star",
            "criteria": {
                "Manufacturer": "Philips",
                "SeriesDescription": "sSUM",
                "ProtocolName": "sSUM"
            }
        },         
        {
            "dataType": "anat",
            "modalityLabel": "T2star",
            "criteria": {
                "SeriesDescription": "GRE-ME",
                "ProtocolName": "GRE-ME"
            }
        },    
        {
            "dataType": "dwi",
            "modalityLabel": "dwi",
            "criteria": {
                "SeriesDescription": "DWI",
                "ProtocolName": "*DWI"
                }
        },    
        {
            "dataType": "dwi",
            "modalityLabel": "acq-b0_dwi",
            "criteria": {
                "SeriesDescription": "DWI_b0",
                "ProtocolName": "DWI_b0"
                }
        }
    ]
}

~~~

</details>

@cbedetti I will send you the dataset in a private email.

**Comment by jcohenadad** [comment] 2019-05-07 20:18
@alexfoias you can post the data there, i give my consent ;-)

**Comment by neurolabusc** [comment] 2019-05-07 20:24
the _e1, _e2 and _e3 files suggest dcm2niix detected the echoes. Any reason you are not using the current stable release of dcm2niix ([v1.0.20190410](https://github.com/rordenlab/dcm2niix/releases))?

**Comment by jcohenadad** [comment] 2019-05-07 20:32
@alexfoias maybe you want to be a bit more specific about what behaviour you expect (and potential fixes). It would be easy to add the _e? into your config file, but that's not what the problem is, right?

I suspect the behaviour you expect is for dcm2bids to concatenate all echoes across time into a single 4D volume. So, the question would be: does dcm2bids have the capabilities to do it, if not would that be a welcomed feature?

**Comment by neurolabusc** [comment] 2019-05-07 21:45
Note that the dcm2niix parameter `-m y` will merge volumes in a series even if they vary by something like TE. In general I would discourage this, but it is possible.

**Comment by alexfoias** [comment] 2019-05-08 19:42
@neurolabusc Thank you for your suggestions.
I tried running using dcm2niix (v1.0.20190410), but the behaviour remains the same.
Here is my terminal output:
<details>

~~~

alex:~ $ dcm2bids -d /Users/alfoi/Desktop/glen -p sub-glen -c /Users/alfoi/code/Dcm2Bids/config_spine.txt -o /Users/alfoi/Desktop/glen
INFO:dcm2bids:--- dcm2bids start ---
INFO:dcm2bids:subprocess: dcm2niix
INFO:dcm2bids:
Chris Rorden's dcm2niiX version v1.0.20190410  (JP2:OpenJPEG) (JP-LS:CharLS) Clang8.1.0 (64-bit MacOS)
usage: dcm2niix [options] <in_folder>
 Options :
  -1..-9 : gz compression level (1=fastest..9=smallest, default 6)
  -a : adjacent DICOMs (images from same series always in same folder) for faster conversion (n/y, default n)
  -b : BIDS sidecar (y/n/o [o=only: no NIfTI], default y)
   -ba : anonymize BIDS (y/n, default y)
  -c : comment stored in NIfTI aux_file (provide up to 24 characters)
  -d : directory search depth. Convert DICOMs in sub-folders of in_folder? (0..9, default 5)
  -e : export as NRRD instead of NIfTI (y/n, default n)
  -f : filename (%a=antenna (coil) name, %b=basename, %c=comments, %d=description, %e=echo number, %f=folder name, %i=ID of patient, %j=seriesInstanceUID, %k=studyInstanceUID, %m=manufacturer, %n=name of patient, %p=protocol, %r=instance number, %s=series number, %t=time, %u=acquisition number, %v=vendor, %x=study ID; %z=sequence name; default '%f_%p_%t_%s')
  -g : generate defaults file (y/n/o/i [o=only: reset and write defaults; i=ignore: reset defaults], default n)
  -h : show help
  -i : ignore derived, localizer and 2D images (y/n, default n)
  -l : losslessly scale 16-bit integers to use dynamic range (y/n, default n)
  -m : merge 2D slices from same series regardless of study time, echo, coil, orientation, etc. (y/n, default n)
  -n : only convert this series number - can be used up to 16 times (default convert all)
  -o : output directory (omit to save to input folder)
  -p : Philips precise float (not display) scaling (y/n, default y)
  -r : rename instead of convert DICOMs (y/n, default n)
  -s : single file mode, do not convert other images in folder (y/n, default n)
  -t : text notes includes private patient details (y/n, default n)
  -u : up-to-date check
  -v : verbose (n/y or 0/1/2 [no, yes, logorrheic], default 0)
  -w : write behavior for name conflicts (0,1,2, default 2: 0=skip duplicates, 1=overwrite, 2=add suffix)
  -x : crop 3D acquisitions (y/n/i, default n, use 'i'gnore to neither crop nor rotate 3D acquistions)
  -z : gz compress images (y/o/i/n/3, default y) [y=pigz, o=optimal pigz, i=internal:zlib, n=no, 3=no,3D]
 Defaults file : /Users/alfoi/.dcm2nii.ini
 Examples :
  dcm2niix /Users/chris/dir
  dcm2niix -c "my comment" /Users/chris/dir
  dcm2niix -o /users/cr/outdir/ -z y ~/dicomdir
  dcm2niix -f %p_%s -b y -ba n ~/dicomdir
  dcm2niix -f mystudy%s ~/dicomdir
  dcm2niix -o "~/dir with spaces/dir" ~/dicomdir

INFO:dcm2bids:dcm2niix:version: v1.0.20190410
INFO:dcm2bids:participant: sub-glen
INFO:dcm2bids:session: None
INFO:dcm2bids:config: /Users/alfoi/code/Dcm2Bids/config_spine.txt
INFO:dcm2bids:BIDS directory: /Users/alfoi/Desktop/glen
INFO:dcm2bids:
INFO:dcm2bids:--- running dcm2niix ---
INFO:dcm2bids:subprocess: dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen /Users/alfoi/Desktop/glen
INFO:dcm2bids:
Chris Rorden's dcm2niiX version v1.0.20190410  (JP2:OpenJPEG) (JP-LS:CharLS) Clang8.1.0 (64-bit MacOS)
Found 1032 DICOM file(s)
Philips Scaling Values RS:RI:SS = 10.03:0:0.0033502 (see PMC3998685)
Convert 192 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/201_glen_WIP_T1w_SENSE_20171128160324 (256x256x192x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/201_glen_WIP_T1w_SENSE_20171128160324.nii"
swizzling 3rd and 4th dimensions (XYTZ -> XYZT), assuming interslice distance is 4.999999
Philips Scaling Values RS:RI:SS = 3.79536:0:0.000695347 (see PMC3998685)
Convert 44 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/801_glen_WIP_GRE-MT_SENSE_20171128160324 (256x256x22x2)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/801_glen_WIP_GRE-MT_SENSE_20171128160324.nii"
swizzling 3rd and 4th dimensions (XYTZ -> XYZT), assuming interslice distance is 5.000000
Saving 33 DTI gradients. Validate vectors.
Philips Scaling Values RS:RI:SS = 11.1116:0:0.00972837 (see PMC3998685)
Convert 495 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/401_glen_WIP_DWI_CLEAR_20171128160324 (64x64x15x33)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/401_glen_WIP_DWI_CLEAR_20171128160324.nii"
Philips Scaling Values RS:RI:SS = 1:0:0.296578 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/1002_glen_sSUM_20171128160324 (320x320x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/1002_glen_sSUM_20171128160324.nii"
slices not stacked: echo varies (TE 2.14, 15.401; echo 1, 3). Use 'merge 2D slices' option to force stacking
Philips Scaling Values RS:RI:SS = 13.6796:0:0.0585914 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/1001_glen_WIP_GRE-ME_5mm_CLEAR_20171128160324_e1 (320x320x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/1001_glen_WIP_GRE-ME_5mm_CLEAR_20171128160324_e1.nii"
Philips Scaling Values RS:RI:SS = 11.1116:0:0.00972837 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/402_glen_facFAc_20171128160324 (64x64x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/402_glen_facFAc_20171128160324.nii"
Philips Scaling Values RS:RI:SS = 13.6796:0:0.0585914 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/1001_glen_WIP_GRE-ME_5mm_CLEAR_20171128160324_e3 (320x320x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/1001_glen_WIP_GRE-ME_5mm_CLEAR_20171128160324_e3.nii"
swizzling 3rd and 4th dimensions (XYTZ -> XYZT), assuming interslice distance is 4.999999
Philips Scaling Values RS:RI:SS = 4.34921:0:0.000689107 (see PMC3998685)
Convert 44 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/501_glen_WIP_GRE-MT_ProSet_SENSE_20171128160324 (256x256x22x2)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/501_glen_WIP_GRE-MT_ProSet_SENSE_20171128160324.nii"
Philips Scaling Values RS:RI:SS = 13.6796:0:0.0585914 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/1001_glen_WIP_GRE-ME_5mm_CLEAR_20171128160324_e2 (320x320x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/1001_glen_WIP_GRE-ME_5mm_CLEAR_20171128160324_e2.nii"
Philips Scaling Values RS:RI:SS = 4.45177:0:0.000688301 (see PMC3998685)
Convert 22 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/901_glen_WIP_GRE-T1_SENSE_20171128160324 (256x256x22x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/901_glen_WIP_GRE-T1_SENSE_20171128160324.nii"
slices not stacked: orientation varies (vNav or localizer?) [0 1 0 0 0 -1] != [1 0 0 0 0 -1]
Philips Scaling Values RS:RI:SS = 4.11941:0:0.112872 (see PMC3998685)
Convert 3 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/101_glen_WIP_SURVEY_CLEAR_20171128160324_i00007 (320x320x3x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/101_glen_WIP_SURVEY_CLEAR_20171128160324_i00007.nii"
Philips Scaling Values RS:RI:SS = 2.2464:0:0.00137913 (see PMC3998685)
Convert 63 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/301_glen_WIP_T2w_SENSE_20171128160324 (320x320x63x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/301_glen_WIP_T2w_SENSE_20171128160324.nii"
Philips Scaling Values RS:RI:SS = 4.27863:0:0.000689843 (see PMC3998685)
Convert 22 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/601_glen_WIP_GRE-T1_ProSet_SENSE_20171128160324 (256x256x22x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/601_glen_WIP_GRE-T1_ProSet_SENSE_20171128160324.nii"
Philips Scaling Values RS:RI:SS = 19.9807:0:0.0586615 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/701_glen_WIP_GRE-ME_CLEAR_20171128160324_e2 (320x320x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/701_glen_WIP_GRE-ME_CLEAR_20171128160324_e2.nii"
Philips Scaling Values RS:RI:SS = 19.9807:0:0.0586615 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/701_glen_WIP_GRE-ME_CLEAR_20171128160324_e3 (320x320x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/701_glen_WIP_GRE-ME_CLEAR_20171128160324_e3.nii"
Philips Scaling Values RS:RI:SS = 19.9807:0:0.0586615 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/701_glen_WIP_GRE-ME_CLEAR_20171128160324_e1 (320x320x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/701_glen_WIP_GRE-ME_CLEAR_20171128160324_e1.nii"
Philips Scaling Values RS:RI:SS = 4.11941:0:0.112872 (see PMC3998685)
Convert 3 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/101_glen_WIP_SURVEY_CLEAR_20171128160324_i00001 (320x320x3x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/101_glen_WIP_SURVEY_CLEAR_20171128160324_i00001.nii"
Philips Scaling Values RS:RI:SS = 4.11941:0:0.112872 (see PMC3998685)
Convert 3 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/101_glen_WIP_SURVEY_CLEAR_20171128160324_i00004 (320x320x3x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/101_glen_WIP_SURVEY_CLEAR_20171128160324_i00004.nii"
Philips Scaling Values RS:RI:SS = 1:0:0.424415 (see PMC3998685)
Convert 15 DICOM as /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/702_glen_sSUM_20171128160324 (320x320x15x1)
Compress: "/Applications/MRIcroGL/pigz_mricron" -b 960 -n -f -6 "/Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen/702_glen_sSUM_20171128160324.nii"
Conversion required 2.361514 seconds (1.037733 for core code).

INFO:dcm2bids:
INFO:dcm2bids:Sidecars matching:
INFO:dcm2bids:NO MATCH        1001_glen_WIP_GRE-ME_5..20171128160324_e1.json
INFO:dcm2bids:NO MATCH        1001_glen_WIP_GRE-ME_5..20171128160324_e2.json
INFO:dcm2bids:NO MATCH        1001_glen_WIP_GRE-ME_5..20171128160324_e3.json
INFO:dcm2bids:MATCH           1002_glen_sSUM_20171128160324.json
INFO:dcm2bids:NO MATCH        101_glen_WIP_SURVEY_CL..1128160324_i00001.json
INFO:dcm2bids:NO MATCH        101_glen_WIP_SURVEY_CL..1128160324_i00004.json
INFO:dcm2bids:NO MATCH        101_glen_WIP_SURVEY_CL..1128160324_i00007.json
INFO:dcm2bids:NO MATCH        201_glen_WIP_T1w_SENSE_20171128160324.json
INFO:dcm2bids:NO MATCH        301_glen_WIP_T2w_SENSE_20171128160324.json
INFO:dcm2bids:NO MATCH        401_glen_WIP_DWI_CLEAR_20171128160324.json
INFO:dcm2bids:NO MATCH        402_glen_facFAc_20171128160324.json
INFO:dcm2bids:NO MATCH        501_glen_WIP_GRE-MT_Pr..SE_20171128160324.json
INFO:dcm2bids:MATCH           601_glen_WIP_GRE-T1_Pr..SE_20171128160324.json
INFO:dcm2bids:NO MATCH        701_glen_WIP_GRE-ME_CLEAR_20171128160324_e1.json
INFO:dcm2bids:NO MATCH        701_glen_WIP_GRE-ME_CLEAR_20171128160324_e2.json
INFO:dcm2bids:NO MATCH        701_glen_WIP_GRE-ME_CLEAR_20171128160324_e3.json
INFO:dcm2bids:MATCH           702_glen_sSUM_20171128160324.json
INFO:dcm2bids:NO MATCH        801_glen_WIP_GRE-MT_SENSE_20171128160324.json
INFO:dcm2bids:MATCH           901_glen_WIP_GRE-T1_SENSE_20171128160324.json
INFO:dcm2bids:
INFO:dcm2bids:Checking if a description matches several sidecars ...
INFO:dcm2bids:'T2star' has several runs
INFO:dcm2bids:'acq-T1w_MTS' has several runs
INFO:dcm2bids:
INFO:dcm2bids:moving acquisitions into BIDS output directory

~~~

</details>

I added the dcm2niix parameter `-m y` in the [dcm2niix.py](https://github.com/cbedetti/Dcm2Bids/blob/master/dcm2bids/dcm2niix.py) and reinstalled dcm2bids. The problem is that not it merges all the volumes. The idea would be that the parameter would be triggered only when multiple echoes are present.

Here is my output with the added parameter:
<details>

~~~

alex:~/code/Dcm2Bids $ dcm2bids -d /Users/alfoi/Desktop/glen -p sub-glen -c /Users/alfoi/code/Dcm2Bids/config_spine.txt -o /Users/alfoi/Desktop/glen 
INFO:dcm2bids:--- dcm2bids start ---
INFO:dcm2bids:subprocess: dcm2niix
INFO:dcm2bids:
Chris Rorden's dcm2niiX version v1.0.20190410  (JP2:OpenJPEG) (JP-LS:CharLS) Clang8.1.0 (64-bit MacOS)
usage: dcm2niix [options] <in_folder>
 Options :
  -1..-9 : gz compression level (1=fastest..9=smallest, default 6)
  -a : adjacent DICOMs (images from same series always in same folder) for faster conversion (n/y, default n)
  -b : BIDS sidecar (y/n/o [o=only: no NIfTI], default y)
   -ba : anonymize BIDS (y/n, default y)
  -c : comment stored in NIfTI aux_file (provide up to 24 characters)
  -d : directory search depth. Convert DICOMs in sub-folders of in_folder? (0..9, default 5)
  -e : export as NRRD instead of NIfTI (y/n, default n)
  -f : filename (%a=antenna (coil) name, %b=basename, %c=comments, %d=description, %e=echo number, %f=folder name, %i=ID of patient, %j=seriesInstanceUID, %k=studyInstanceUID, %m=manufacturer, %n=name of patient, %p=protocol, %r=instance number, %s=series number, %t=time, %u=acquisition number, %v=vendor, %x=study ID; %z=sequence name; default '%f_%p_%t_%s')
  -g : generate defaults file (y/n/o/i [o=only: reset and write defaults; i=ignore: reset defaults], default n)
  -h : show help
  -i : ignore derived, localizer and 2D images (y/n, default n)
  -l : losslessly scale 16-bit integers to use dynamic range (y/n, default n)
  -m : merge 2D slices from same series regardless of study time, echo, coil, orientation, etc. (y/n, default n)
  -n : only convert this series number - can be used up to 16 times (default convert all)
  -o : output directory (omit to save to input folder)
  -p : Philips precise float (not display) scaling (y/n, default y)
  -r : rename instead of convert DICOMs (y/n, default n)
  -s : single file mode, do not convert other images in folder (y/n, default n)
  -t : text notes includes private patient details (y/n, default n)
  -u : up-to-date check
  -v : verbose (n/y or 0/1/2 [no, yes, logorrheic], default 0)
  -w : write behavior for name conflicts (0,1,2, default 2: 0=skip duplicates, 1=overwrite, 2=add suffix)
  -x : crop 3D acquisitions (y/n/i, default n, use 'i'gnore to neither crop nor rotate 3D acquistions)
  -z : gz compress images (y/o/i/n/3, default y) [y=pigz, o=optimal pigz, i=internal:zlib, n=no, 3=no,3D]
 Defaults file : /Users/alfoi/.dcm2nii.ini
 Examples :
  dcm2niix /Users/chris/dir
  dcm2niix -c "my comment" /Users/chris/dir
  dcm2niix -o /users/cr/outdir/ -z y ~/dicomdir
  dcm2niix -f %p_%s -b y -ba n ~/dicomdir
  dcm2niix -f mystudy%s ~/dicomdir
  dcm2niix -o "~/dir with spaces/dir" ~/dicomdir

INFO:dcm2bids:dcm2niix:version: v1.0.20190410
INFO:dcm2bids:participant: sub-glen
INFO:dcm2bids:session: None
INFO:dcm2bids:config: /Users/alfoi/code/Dcm2Bids/config_spine.txt
INFO:dcm2bids:BIDS directory: /Users/alfoi/Desktop/glen
INFO:dcm2bids:
INFO:dcm2bids:--- running dcm2niix ---
INFO:dcm2bids:subprocess: dcm2niix -b y -ba y -z y -f '%3s_%f_%p_%t' -o /Users/alfoi/Desktop/glen/tmp_dcm2bids/sub-glen /Users/alfoi/Desktop/glen -m y
INFO:dcm2bids:
Chris Rorden's dcm2niiX version v1.0.20190410  (JP2:OpenJPEG) (JP-LS:CharLS) Clang8.1.0 (64-bit MacOS)
Example output filename: '/001_myFolder_MPRAGE_19770703150928.nii.gz'

INFO:dcm2bids:
INFO:dcm2bids:Sidecars matching:
INFO:dcm2bids:
INFO:dcm2bids:Checking if a description matches several sidecars ...
INFO:dcm2bids:
INFO:dcm2bids:moving acquisitions into BIDS output directory

~~~

</details>

**Comment by arnaudbore** [comment] 2020-11-17 16:25
@alexfoias @jcohenadad  do you still have this issue or can I close it ?

**Comment by jcohenadad** [comment] 2020-11-17 16:34
@alexfoias I believe this issue was caused by a research sequence running on an old software version (context: https://github.com/spine-generic/data-single-subject/issues/7). So we can close.

**Closed by jcohenadad** 2020-11-17 16:34 UTC
