### ISSUE TITLE
dcm2bids not ordering runs chronologically

### ISSUE THREAD

**Issue by dasturge** [UNFmontreal/Dcm2Bids#34] opened 2018-10-19 20:13 UTC
We have cases where the order of task-rest data has been changed after conversion.  The end sidecar jsons have been mapped [3rd, 4th, 1st, 2nd] -> [run-01, run-02, run-03, run-04].

how is the ordering currently determined?

the Acquisition Time in the sidecar jsons for run-03 and run-04 have earlier times than run-01 and run-02. Is there are reason it shouldn't be sorted by AcquisitionTime in the first place?

I can work with you to test/discover where the error is occurring.  I may be able to share the data under certain circumstances.

EDIT:
I have discovered the source of the problem.

Some dicom Series Numbers are padded with a double zero at the end, .e.g.,  the 4th scan would be 400.  This seems to have to do with acquisition parameters unique to those modalities.  Within the code, it assumes that a standard ASCII sort will work because small Series Numbers (1, 2,... 99) are padded with 0s to be three digits long, however these 00-padded modalities are not padded in this manner.

This bug will occur in the case that a given task is 00-padded by the scanner, and is acquired as the (1st..9th) series, then acquired additional times as 10th or later series...

e.g.
tmp_dcm2bids/sub-name/
  008_sub-name-desc_date.json  # not padded by scanner, 8th run
  009_sub-name-desc_date.json  # not padded by scanner, 9th run
  1000_sub-name-desc2_date.json  # this is actually the 10th run, 00-padded
  700_sub-name-desc2_date.json  # this is actually the 7th run, 00-padded, but sorted chronologically later
  
I don't know the reason why Philips/GE are using this 00-pad, I will try to find out.

**Comment by dasturge** [comment] 2018-10-19 21:58
After more investigation, we've noticed that the issue may not be present in SIEMENS but is present for GE and PHILIPS data.

**Comment by cbedetti** [comment] 2019-03-10 20:27
This should be corrected in 2.0.0 but I don't have PHILIPS data to test it

**Comment by arnaudbore** [comment] 2019-03-13 18:32
@dasturge can you test it again, I've got some PHILIPS data as well but was not able to replicate your issue.

**Comment by dasturge** [comment] 2019-03-13 20:16
@arnaudbore I should be able to give it a go in the next week or so, I'll post back with the results.

**Comment by jcohenadad** [comment] 2019-04-05 19:50
@dasturge do you have any feedback? Can the issue be closed?

**Comment by dasturge** [comment] 2019-04-08 22:26
@jcohenadad sorry, I have someone testing this now. Thanks for your patience.

**Comment by dasturge** [comment] 2019-04-11 18:16
@jcohenadad so unfortunately this doesn't seem to fix our issue. 

However, I believe the problem is occurring due to some software mucking up the dicom metadata. I believe the code which does this was acquired directly from PHILIPS, but I'm checking with our collaborators to confirm.

**Comment by arnaudbore** [comment] 2019-04-11 18:21
Can you make some dcm from Philips available so we can reproduce and fix it quickly (if possible) ?

**Comment by dasturge** [comment] 2019-04-11 19:06
@arnaudbore if you sign a Data Use Certification for the ABCD study, we can provide you with a subject's dicoms where this error occurs: https://nda.nih.gov/abcd/request-access

I have confirmed that the GE data where we had the issue was due to a GE script which padded the series number, the PHILIPS data is apparently as-is.

**Comment by CerenB** [comment] 2020-09-30 15:46
Not sure if someone would like to improve dcm2bids for GE scanner but I can confirm that for GE output, the issue is still there. 
To be more precise, SeriesNumber = [3, 4, 11, 6, 5, 10] corresponding to the output of dcm2bids RunNumber = [1, 2, 3, 4, 5, 6]. In this example, SeriesNumber 1 and 2 are omitted, they were loc and anat images. I have not figured out the logic there but it seems the padding issue. 
Any suggestions? I'd be happy to provide the data if needed.

**Comment by arnaudbore** [comment] 2020-11-17 16:15
@CerenB if you can send me some data I will be happy to fix this issue.

**Comment by CerenB** [comment] 2020-12-03 18:42
@arnaudbore thank you! it might be due to GE producing extra files and they are messing up the order, still not 100% sure. How can I share the data with you?

**Comment by arnaudbore** [comment] 2020-12-03 18:58
@CerenB you can use [https://wetransfer.com/](https://wetransfer.com/).

**Comment by arnaudbore** [comment] 2020-12-07 21:09
@CerenB  can you test with this PR #68 ? I found something that may be the issue you were talking about.

**Comment by CerenB** [comment] 2020-12-08 10:39
> @CerenB can you test with this PR #68 ? I found something that may be the issue you were talking about.

thanks! it's true that my config.json has upper and lower cases but it's identical to the how Series/Protocol names are called in sidecar. But I am using the latest version of dcm2bids, that should have been resolved in this version?

**Comment by CerenB** [comment] 2021-01-04 15:29
That PR #68 solved my issue with GE scanner run number organisation. Thank you!

**Closed** 2021-01-04 17:47 UTC
